receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"
            - "http://127.0.0.1:3000"
          allowed_headers: ["*"]
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317" # Send traces to Jaeger using OTLP gRPC
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9090" # Expose metrics on this endpoint
    namespace: "otel_brew"
  debug:
    verbosity: detailed

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
